# Generated by Django 4.2 on 2023-06-26 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('contents', models.CharField(max_length=200, verbose_name='需求')),
                ('times', models.CharField(max_length=200, verbose_name='时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_addresses', to='areas.area', verbose_name='市')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_addresses', to='areas.area', verbose_name='区')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_addresses', to='areas.area', verbose_name='省')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '需求博客',
                'verbose_name_plural': '需求博客',
                'db_table': 'tb_blogs',
            },
        ),
    ]
